name: Build test with PyCrucible action

on:
  push:

permissions:
  contents: write

jobs:
  run_test_app:
    name: Smoke Test PyCrucible action
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # ----- Linux -----
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin_ext: ""
          # ----- Windows -----
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            bin_ext: ".exe"
          # ----- macOS -----
          - runner: macos-13
            target: x86_64-apple-darwin
            bin_ext: ""

    steps:
      - uses: actions/checkout@v4
      - name: Print out the current dir
        run: pwd
      - name: Print out LS
        run: ls
      - name: Use GitHub action
        uses: razorblade23/pycrucible-action@v1.0.5
        with:
            entry: .
            output: ./cowsay

      - name: Smoke-test generated artifact (Linux and MacOS)
        if: runner.os != 'Windows'
        run: ./cowsay

      - name: Smoke-test generated artifact (Windows)
        run: cowsay.exe
